### ISSUE TITLE
Local HTTPS 

### ISSUE THREAD

**Issue by matthall8** [FACN4/StudentProject-WeCook#10]
- Spike on how to set-up HTTPS locally
- Share with team information on how to do it.
- Ensure all team members have set it up successfully.

**Comment by DenisKent** [comment]
Chrom warning message shown is this: 
![image](https://user-images.githubusercontent.com/28222381/45293262-5118b000-b500-11e8-923e-90f819cdf2d3.png)

**Comment by matthall8** [comment]
Spike complete and relevant information is on everyone's laptop.
