### ISSUE TITLE
Draw Schema

### ISSUE THREAD

**Issue by DenisKent** [FACN4/StudentProject-WeCook#11]
![img_1204](https://user-images.githubusercontent.com/28222381/45264470-9cba5380-b445-11e8-9e11-5c637fc84729.JPG)

**Comment by DenisKent** [comment]
![image](https://user-images.githubusercontent.com/28222381/45265291-2de2f780-b451-11e8-8610-5546a9ba63c5.png)

**Comment by noorafi** [comment]
Added to the readme https://github.com/FACN4/StudentProject-WeCook/wiki/Schemas

**Comment by DenisKent** [comment]
Update
![image](https://user-images.githubusercontent.com/28222381/45286349-3c332100-b4ee-11e8-9457-814f4d8d1070.png)

**Comment by matthall8** [comment]
Completed as per above.

**Comment by DenisKent** [comment]
![image](https://user-images.githubusercontent.com/28222381/45351530-19247200-b5bf-11e8-832d-c5a38a43a93a.png)

**Comment by DenisKent** [comment]
![image](https://user-images.githubusercontent.com/28222381/45352237-b633da80-b5c0-11e8-94b6-f95383e66f87.png)

**Comment by shiryz** [comment]
reopening issue since you're still commenting on this

**Comment by DenisKent** [comment]
![image](https://user-images.githubusercontent.com/28222381/45360783-48e07380-b5d9-11e8-8d1f-4b64b88bd4fd.png)

**Comment by DenisKent** [comment]
![image](https://user-images.githubusercontent.com/28222381/45737762-5f995280-bbf7-11e8-8dae-b6892e224da6.png)
