### ISSUE TITLE
redux 

### ISSUE THREAD

**Issue by noorafi** [FACN4/StudentProject-WeCook#15]
spike

**Comment by shiryz** [comment]
Should have more description when working on this, and maybe adding the progress as you go.
Would recommend commenting with useful resources :running_man:

**Comment by DenisKent** [comment]
Spike using video series. The files have been shared with the team via usb. Also used a Redux tutorial done online: 
https://www.youtube.com/watch?v=93p3LxR9xfM

**Comment by matthall8** [comment]
Spike complete as per above.
