### ISSUE TITLE
Header component

### ISSUE THREAD

**Issue by noorafi** [FACN4/StudentProject-WeCook#18]
Epic: Create Header component

-----

Linked Issues: 

- [x] Create base HTML - #42
- [x] Create base CSS - #43
------
*User story*: As a user, I want to be able to view my basket, navigate back to the homepage by clicking the logo and also log in or view my profile if I'm already logged in.

**Comment by shiryz** [comment]
Please provide a user story when working on this

**Comment by matthall8** [comment]
User story: As a user, I want to be able to view my basket, navigate back to the homepage by clicking the logo and also log in or view my profile if I'm already logged in.

**Comment by shiryz** [comment]
Description updated with the user story, it's easier to follow if you have the details in the description

**Comment by shiryz** [comment]
This is an epic, I expect to see a bit more detail on what you're working on, I want to see linked issues in the description :tada:
