### ISSUE TITLE
Add review stars component

### ISSUE THREAD

**Issue by DenisKent** [FACN4/StudentProject-WeCook#29]
A user should be able to quickly glance at cook information and have an idea of how trustworthy they are. Stars using sprite is a potential solution

**Comment by shiryz** [comment]
Please add some description, a user story and more issues when working on this.

**Comment by DenisKent** [comment]
![frame 1](https://user-images.githubusercontent.com/28222381/45496829-fe006080-b77e-11e8-88f1-7701870e7c4f.png)

I made this sprite to use in the css

**Comment by DenisKent** [comment]
![frame 2](https://user-images.githubusercontent.com/28222381/45497282-10c76500-b780-11e8-93f9-1a58add8fc4f.png)
Fixed the sprite
