### ISSUE TITLE
Dummy photos

### ISSUE THREAD

**Issue by DenisKent** [FACN4/StudentProject-WeCook#35]
![calum-lewis-387582-unsplash](https://user-images.githubusercontent.com/28222381/45268630-08251500-b488-11e8-94c4-7e664f5d45c9.jpg)

![maarten-van-den-heuvel-400626-unsplash](https://user-images.githubusercontent.com/28222381/45268635-2db21e80-b488-11e8-95c3-cf0569d3d045.jpg)

![daria-shevtsova-426317-unsplash](https://user-images.githubusercontent.com/28222381/45268646-3c98d100-b488-11e8-82a5-cebcf5b23b24.jpg)

![making-food-982410_1920](https://user-images.githubusercontent.com/28222381/45268673-bc26a000-b488-11e8-8b53-478f8b669842.jpg)

**Comment by DenisKent** [comment]
![kebab-plate-with-spicy](https://user-images.githubusercontent.com/28222381/45268801-1163b100-b48b-11e8-85b0-d32b09a111e3.jpg)
![bbq](https://user-images.githubusercontent.com/28222381/45268805-1c1e4600-b48b-11e8-932f-ddae68a9bd3c.jpg)
![jenn-kosar-584036-unsplash](https://user-images.githubusercontent.com/28222381/45268810-37895100-b48b-11e8-8b5d-c6e8964b4f2b.jpg)
![caroline-attwood-243834-unsplash](https://user-images.githubusercontent.com/28222381/45268814-4ff96b80-b48b-11e8-88ba-f9e7fa57dc22.jpg)

**Comment by DenisKent** [comment]
@shiryz, I just wanted to save some images reliably rather than using online links. So I created an issue to save them and then closed it.

**Comment by shiryz** [comment]
It's better if you close it once you use these pics :ok_hand:

**Comment by DenisKent** [comment]
Home screen: 
![toa-heftiba-616938-unsplash](https://user-images.githubusercontent.com/28222381/45624675-ab32eb80-ba93-11e8-850a-4c3a321b8622.jpg)

**Comment by DenisKent** [comment]
![rectangle](https://user-images.githubusercontent.com/28222381/45626954-72961080-ba99-11e8-9215-538504f985ea.jpg)

**Comment by DenisKent** [comment]
![map](https://user-images.githubusercontent.com/28222381/45644633-dedb3900-bac6-11e8-8838-07261915f486.jpg)
![time](https://user-images.githubusercontent.com/28222381/45644814-4e512880-bac7-11e8-842b-9f3310232676.jpg)
)

**Comment by DenisKent** [comment]
![main](https://user-images.githubusercontent.com/28222381/45745334-4bf6e780-bc09-11e8-9d21-98e0f85aa181.png)
![image](https://user-images.githubusercontent.com/28222381/45745411-734db480-bc09-11e8-9659-722685bc462f.png)
![image](https://user-images.githubusercontent.com/28222381/45745431-82ccfd80-bc09-11e8-91b8-7a02b82a1a3a.png)
![image](https://user-images.githubusercontent.com/28222381/45745458-911b1980-bc09-11e8-8086-c6bbfc5bae2b.png)

**Comment by matthall8** [comment]
![phone-call 1](https://user-images.githubusercontent.com/9437789/45783447-7333d000-bc6e-11e8-88ad-33f05f399c99.png)
![group 1](https://user-images.githubusercontent.com/9437789/45783448-73cc6680-bc6e-11e8-98de-c5ea235f98a2.jpg)
![image 1](https://user-images.githubusercontent.com/9437789/45783449-73cc6680-bc6e-11e8-9e2d-ec03c86b8b41.png)
![group 1](https://user-images.githubusercontent.com/9437789/45783450-73cc6680-bc6e-11e8-8013-49f366bef3d8.png)

**Comment by DenisKent** [comment]
![rectangle2imgad](https://user-images.githubusercontent.com/28222381/45878093-906cb980-bda8-11e8-9534-61322b3c14c7.png)

**Comment by matthall8** [comment]
![ezgif-1-108441b5d9](https://user-images.githubusercontent.com/9437789/45885721-d2edc080-bdbf-11e8-9789-b6332caf76a3.gif)
