### ISSUE TITLE
Travis + Heroku setup

### ISSUE THREAD

**Issue by matthall8** [FACN4/StudentProject-WeCook#8]
Set-up the project up in Travis and Heroku.

**Comment by DenisKent** [comment]
It has been created.
Site link: https://we-cook.herokuapp.com/

**Comment by noorafi** [comment]
Looks like Travis is working too: 
![image](https://user-images.githubusercontent.com/33840142/45265622-6b964f00-b456-11e8-8047-3aa62dccebba.png)

**Comment by matthall8** [comment]
Completed as per above.
